// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxF2F8X1qdC2cseoxtg0hGJldJYsty8X8',
    appId: '1:213317608636:web:cb7a52b4ab99d3dcdc9cb9',
    messagingSenderId: '213317608636',
    projectId: 'scorekeep-ffa31',
    authDomain: 'scorekeep-ffa31.firebaseapp.com',
    storageBucket: 'scorekeep-ffa31.firebasestorage.app',
    measurementId: 'G-DP0XTDWFXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_9ZyDSNWeSwSEWC8irhn6G0r7fP500Y',
    appId: '1:213317608636:android:8b55ba428c781309dc9cb9',
    messagingSenderId: '213317608636',
    projectId: 'scorekeep-ffa31',
    storageBucket: 'scorekeep-ffa31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhEbOaNL-k66wKG_P722hFXFNhFqTRphc',
    appId: '1:213317608636:ios:d46f6a2b059bf2c4dc9cb9',
    messagingSenderId: '213317608636',
    projectId: 'scorekeep-ffa31',
    storageBucket: 'scorekeep-ffa31.firebasestorage.app',
    iosBundleId: 'com.score.keep',
  );

}